### ISSUE TITLE
Cannot build CrystalSpace 3D on Debian Jessie

### ISSUE THREAD

**Issue by aladedragon** [roman-yagodin/PlaneShift.BuildScripts#4]
Hello from Spain  :dancer: 
PS has moved the svn repo in SF to the new url:

svn co https://svn.code.sf.net/p/planeshift/code/trunk planeshift 
You can have a look to the new compiling guide.
At the moment on debian Jessie is not running properly the CS configuration process, but is not refereed to your script, so I can't provide you feedback at the moment, just there are a few differences about version in packages but I need to investigate it.
Thanks for the work :)

**Comment by roman-yagodin** [comment]
Greetings from Russia, @aladedragon!
Thanks, I will look at it as soon as I have some free time.

**Comment by roman-yagodin** [comment]
CS configuration is broken on Jessie, indeed - it hangs on `config.status: executing Makefile commands`. Removing automake (1.14) and automake1.11 packages have no effect.

**Comment by aladedragon** [comment]
Привет, я говорю мало по-русский. :)
I'm testing now about libcurl. It seems that is trying some kind of ssh/cvs connexion to crystalspace.org 
I have opened a threat at cs mailing list.
https://sourceforge.net/p/crystal/mailman/message/34175979/
They ask me about a "config.log" that is not generated in my system. trying now to do some proves on virtual machine.

**Comment by roman-yagodin** [comment]
As I realized now, `configure` script produces `config.log`, but delete it after `executing Makefile commands stage`. Strangely, on this stage configure perform build of CS, as there are compiler output in the log (but not in the console). After that (it take long enough), script ask:
`The authenticity of host 'crystalspace3d.org (217.115.131.45)' can't be established.
RSA key fingerprint is 9b:55:7a:fe:ea:aa:0e:71:ea:74:65:da:0a:06:91:15.
Are you sure you want to continue connecting (yes/no)?`

**Comment by aladedragon** [comment]
This is the step I was talking about. I can't manage it.
I tried to use whezzy and update just a few of packages in order to see what is wrong, I will investigate a bit more in deep this week, I'm have some things to do  in my daily life.

**Comment by roman-yagodin** [comment]
I think I found a workaround for the issue and currently performing test build. It seems that CS need to be configured with `--enable-make-emulation="no"` flag to skip Makefiles generation and use Jamfiles only.

**Comment by roman-yagodin** [comment]
The workaround indeed working, though build finished with some issues - but it at least configure step now passing OK.

**Comment by aladedragon** [comment]
Thank you for your help Roman.
I will test it in my next update. Debian 7 is going to be under LTS at the end of feb.

**Comment by roman-yagodin** [comment]
Your welcome, @aladedragon! Thanks for feedback.
